#!/usr/bin/env bash
# ARKLinux archiso customise hook
# Called by mkarchiso as: customize_airootfs()
# Working directory: the airootfs chroot root (i.e., / inside the image)
# All commands run inside the chroot via arch-chroot.
# Reference: https://wiki.archlinux.org/title/Archiso#Customize_airootfs

set -euo pipefail

# ── 1. Locale ─────────────────────────────────────────────────────────────────
locale-gen

# ── 2. Timezone ───────────────────────────────────────────────────────────────
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# ── 3. System user: ark (UID 973, no login shell, no home outside /opt/ark) ───
groupadd --system --gid 973 ark 2>/dev/null || true
useradd  --system \
         --uid 973 \
         --gid ark \
         --no-create-home \
         --home-dir /opt/ark \
         --shell /usr/bin/nologin \
         --comment "ARK service account" \
         ark 2>/dev/null || true

# ── 4. /opt/ark state-root scaffold & permissions ────────────────────────────
install -d -m 750 -o ark -g ark \
  /opt/ark \
  /opt/ark/models \
  /opt/ark/ingest \
  /opt/ark/bus \
  /opt/ark/memory \
  /opt/ark/logs \
  /opt/ark/backup \
  /opt/ark/apps \
  /opt/ark/id \
  /opt/ark/agents \
  /opt/ark/run

install -d -m 700 -o ark -g ark \
  /opt/ark/secrets \
  /opt/ark/quarantine

install -d -m 1777 -o ark -g ark \
  /opt/ark/snapshots

install -d -m 755 -o ark -g ark \
  /opt/ark/aletheia \
  /opt/ark/aletheia/audit \
  /opt/ark/aletheia/manifests

# Make aletheia immutable (chattr +i) after populating initial manifest
# Note: chattr is filesystem-level; on overlayfs live env it's a no-op,
# but it protects the installed system post-deployment.
chattr +i /opt/ark/aletheia/manifests 2>/dev/null || true

# ── 5. ARK runtime configuration file ────────────────────────────────────────
cat > /etc/ark/config.toml << 'TOML'
# ARKLinux runtime configuration
# Generated by customize_airootfs — do not edit manually on installed system.
# Use: systemctl edit ark-core.service for overrides.

[ark]
version     = "1.0.1"
state_root  = "/opt/ark"
log_level   = "info"
audit_log   = "/opt/ark/aletheia/audit/events.log"

[ark.agents]
core_bin     = "/usr/local/bin/ark-core"
watchdog_bin = "/usr/local/bin/ark-watchdog"

[ark.security]
fail_closed     = true
quarantine_path = "/opt/ark/quarantine"
manifest_path   = "/opt/ark/aletheia/manifests"

[ark.network]
bind_addr = "127.0.0.1"
egress    = "deny"
TOML

chown root:ark /etc/ark/config.toml
chmod 640 /etc/ark/config.toml

# ── 6. Enable systemd services ────────────────────────────────────────────────
systemctl enable nftables.service
systemctl enable sshd.service
systemctl enable ark-core.service
systemctl enable ark-watchdog.service
systemctl enable ark.target

# ── 7. Disable services not needed in live/installed ARK environment ──────────
systemctl disable dhcpcd.service 2>/dev/null || true
systemctl mask systemd-networkd-wait-online.service 2>/dev/null || true

# ── 8. Inject build metadata into os-release ─────────────────────────────────
BUILD_ID="${BUILD_ID:-$(date -u +%Y%m%dT%H%M%SZ)}"
sed -i "s|@BUILD_ID@|${BUILD_ID}|g" /etc/os-release
echo "BUILD_TIMESTAMP=${BUILD_ID}" >> /etc/os-release

# ── 9. Stamp initial state manifest (Aletheia genesis record) ─────────────────
install -m 644 -o ark -g ark /dev/null /opt/ark/aletheia/manifests/state.json
cat > /opt/ark/aletheia/manifests/state.json << JSON
{
  "version":    "1.0.1",
  "build_id":   "${BUILD_ID}",
  "build_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "kernel":     "$(uname -r 2>/dev/null || echo unknown)",
  "state_root": "/opt/ark",
  "services": [
    "ark-core.service",
    "ark-watchdog.service",
    "ark.target"
  ],
  "security": {
    "nftables": "default-deny",
    "systemd_hardening": "strict",
    "fail_closed": true
  },
  "integrity": "genesis"
}
JSON
chown ark:ark /opt/ark/aletheia/manifests/state.json
chmod 644 /opt/ark/aletheia/manifests/state.json

# ── 10. Verify critical files are present (build-time smoke test) ─────────────
echo "[customize_airootfs] Running build-time assertions..."
assert_present() {
  if [[ ! -e "$1" ]]; then
    echo "ASSERTION FAILED: $1 missing" >&2
    exit 1
  fi
  echo "  OK: $1"
}

assert_present /usr/local/bin/ark-install
assert_present /usr/local/bin/ark-core
assert_present /usr/local/bin/ark-watchdog
assert_present /etc/systemd/system/ark-core.service
assert_present /etc/systemd/system/ark-watchdog.service
assert_present /etc/systemd/system/ark.target
assert_present /etc/systemd/system/ark-quarantine.target
assert_present /etc/nftables.conf
assert_present /opt/ark/aletheia/manifests/state.json
assert_present /etc/ark/config.toml

echo "[customize_airootfs] All assertions passed. Build proceeding."
